export const RECEIVE_ADDRESS = 'receive_address'
export const GET_CATEGORYS = 'get_categorys'
export const GET_SHOPS = 'get_shops'
export const RECEIVE_USER_INFO = 'receive_user_info'
export const RESET_USER_INFO = 'reset_user_info'